num1 = input("enter 1st number")
num2 = input("enter 2nd number")
num3 = input("enter 3rd number")
num4 = input("enter 4th number")
num5 = input("enter 5th number")
print(num1)
print(num2)
print(num3)
print(num4)
print(num5)